### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by olivierlemasle** [casey/temptree#1]
Could you please include a license file in this crate?

I'm currently packaging this crate for Fedora [as part of Just packaging](https://bugzilla.redhat.com/show_bug.cgi?id=1978904). Even when the license does not require the license file to be copied with the software, the [Fedora Licensing Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text) encourages projects to ship the license file with their source code.

**Comment by casey** [comment]
> Could you please include a license file in this crate?

You bet. I just added a license file, bumped the version to 0.0.1, and published to crates.io.

Should I create a new release of `just` that depends on the updated crate?

**Comment by olivierlemasle** [comment]
Thank you!

Yes, it would be great to release a new `just` version, because of the semver incompatibility between 0.0.0 and 0.0.1.

**Comment by casey** [comment]
> Yes, it would be great to release a new `just` version, because of the semver incompatibility between 0.0.0 and 0.0.1.

Sounds good. I bumped the version of `temptree` to 0.1.0, and published `just` 0.9.8 which depends on it. I bumped to `0.1.0` so that in the future, I can bump to `0.1.x` and pick those changes up automatically.
